FROM ubuntu
# Upgrade package index

# add oracle java into candidate list.
RUN apt-get update
RUN apt-get upgrade

RUN apt-get install python-software-properties
RUN apt-get install -y --no-install-recommends software-properties-common
RUN add-apt-repository ppa:webupd8team/java
RUN apt-get update
RUN apt-get upgrade

# install a few other useful packages plus oracle jdk.
RUN apt-get install -y less net-tools vim-tiny openssh-server git oracle-java7-installer


ENV SCALA_VERSION 2.10.4
ENV CDH_VERSION cdh4
ENV SCALA_HOME /opt/scala-$SCALA_VERSION
ENV SPARK_HOME /opt/spark
ENV PATH $SPARK_HOME:$SCALA_HOME/bin:$PATH

# Install Scala
ADD http://www.scala-lang.org/files/archive/scala-$SCALA_VERSION.tgz /
RUN (cd / && gunzip < scala-$SCALA_VERSION.tgz)|(cd /opt && tar -xvf -)
RUN rm /scala-$SCALA_VERSION.tgz

# must install lightdm then use root ssh.
http://www.tuicool.com/articles/FRvAbe
